//wrapper class
public class ProductResponse {
    
    public List<ProductContainer> prodList ;
     public List<ProductContainer> furkan ;




}














/*
{
    "prodList": [
        {
            "wheelDrive": "Front-Wheel Drive",
            "unitPrice": 100.00,
            "productName": "Test Product1",
            "productERPId": "01t78000000eME6AAM",
            "productCode": "112233",
            "isActive": true,
            "gear": "Manual",
            "fuelType": "Diesel",
            "engineCapacity": "1000 to 1500",
            "description": "TESTTT",
            "bodyType": "Sedan"]
        },
"furkan":[{
            "wheelDrive": "Rear-Wheel Drive",
            "unitPrice": 2000.00,
            "productName": "Honda City 1.4",
            "productERPId": "01t78000000eYSoAAM",
            "productCode": "HNCS157965",
            "isActive": true,
            "gear": "Manual",
            "fuelType": "Gasoline",
            "engineCapacity": "1000 to 1500",
            "description": "Honda City is B segment",
            "bodyType": "Sedan"
        },
        {
            "wheelDrive": "4WD (Continuous)",
            "unitPrice": 2500.00,
            "productName": "Test Product 2",
            "productERPId": "01t78000000eMEBAA2",
            "productCode": "223311",
            "isActive": true,
            "gear": "Automatic",
            "fuelType": "Hybrid",
            "engineCapacity": "1500 to 1800",
            "description": null,
            "bodyType": "Station Wagon"
        },
        {
            "wheelDrive": "Front-Wheel Drive",
            "unitPrice": 3000.00,
            "productName": "Honda Accord Sedan 1.6",
            "productERPId": "01t78000000eYStAAM",
            "productCode": "HNAS167854",
            "isActive": true,
            "gear": "Automatic",
            "fuelType": "Gasoline",
            "engineCapacity": "1500 to 1800",
            "description": "Honda Accord is D segment",
            "bodyType": "Sedan"
        },
        {
            "wheelDrive": "Front-Wheel Drive",
            "unitPrice": 2500.00,
            "productName": "Honda Civic Sedan 1.6",
            "productERPId": "01t78000000eYT8AAM",
            "productCode": "123498",
            "isActive": true,
            "gear": "Semi-Automatic",
            "fuelType": "Gasoline",
            "engineCapacity": "1500 to 1800",
            "description": "Honda Civic is C segment",
            "bodyType": "Sedan"
        }
    ]
}

*/





// Yukaridaki prodList adini Furkan olarak heryerde degistirdim ve sonra classim calismadi:
//FATAL_ERROR System.NullPointerException: Attempt to de-reference a null object